### PR TITLE
JFT Layout

### PR DESCRIPTION
**Pull request by klgrimley**
Updates to display either the raw html pulled from jftna.org or a block layout. Block layout includes unique ids and classes.

### CODE REVIEW

**Comment by pjaudiomv** [comment]
cool!! wondering if instead of having the admin dashboard it could be on a seetings page instead of clogging up more dashboard space. maybe even making the settings available as shortcode attributes.

**Comment by klgrimley** [comment]
Could move it as a subpage under the general Settings tab. Yeah, want to work that in as a parameter for the shortcode. Also have a few other ideas but they'll take a bit to figure out the details.

**Comment by pjaudiomv** [comment]
I turned it into a settings page take a look and let me know what you think, its in the master
https://github.com/pjaudiomv/jft/archive/master.zip

**Comment by klgrimley** [comment]
I'm not seeing the settings page show up.

**Comment by pjaudiomv** [comment]
oh no :(. it should be on settings dashboard menu, then Fetch JFT

**Comment by klgrimley** [comment]
Yeah, I see it in the code. I won't have time to look tonight but I can take a look this weekend. I wanted to work on incorporating the Spanish and French versions also at some point too.

**Comment by klgrimley** [comment]
Issue was on my end. However the simple_html_dom.php file is missing and that causes a fatal error since it's a required file. Personally I prefer to keep the admin page code in a separate folder > file so that if/as the plugin grows it's easier to keep track of what's going on where. And I'd also put the simple_html_dom.php inside of an assets folder for the same reason. So the structure would be

**Comment by klgrimley** [comment]
Yeah, the simple html dom both simplifies and complicates the issue. It makes it super quick and easy to run through the elements and grab what we need. However as you pointed out since it's looking for a specific tag it breaks if the layout changes.

**Comment by pjaudiomv** [comment]
cool ive updated the master and moved some things around, idk if you want to work off that for language stuff.

**Comment by klgrimley** [comment]
Yep, that will work.

**Pull request merged**
